:PROPERTIES:
:ID:       F0E09F7E-AF6B-45A9-AED3-6F71DD9EBFBD
:END:
#+title: Komplekse Tall
#+created: [2026-08-21 Fri 12:20]
#+last_modified: [2026-08-21 Fri 12:20]
#+filetags: :mat111:

Part of [[id:7E583AF3-E610-472A-AF5B-80EDA45A794A][MAT111]]
-----

Et komplekst tall er et uttrykk på formen $Z = a + i \cdot b , \quad a , b \in \mathbb{R} , i^2 = - 1$. [[id:2A2C24FA-47C2-43B2-B891-8AD0649E84BD][Mengden]] av slike er $\mathbb{C} = \left\{a + b i \mid a , b \in \mathbb{R} \wedge i^2 = - 1\right\}$.

+ $i$ kalles en /imaginær enhet/.
+ $a = \text{Re} \, Z$: /reell del/
+ $b = \text{Im} \, Z$: /imaginær del/
+ $\overline{Z} = a - i b$ /kompleks konjugert/, "Z-bar"

  Relle tall er en delmengde av de komplekse tallene: $\mathbb{R} = \left\{Z \in \mathbb{C} \mid \text{Im} \, Z = 0\right\}$. Komplekse tall visualiseres vet hjelp av et plan, kalt /det komplekse planet/. Det har en /reell akse/ ($x$-aksen) og en /imaginær akse/ ($y$-aksen).

  Komplekse tall kan også skrives på /polarform/: $Z = \left| Z \right| \cdot \left(\cos \theta + i \cdot \sin \theta\right)$. Den første delen $\left| Z \right| = \sqrt{a^2 + b^2}$ er lengden på vektoren fra origo til punktet i det komplekse planet. Denne kalles /modulus/, og sjeldnere /norm/ eller /absoluttverdi/. Vinkelen $\theta$ er et /argument/ til $Z$. Grunnen til at det er "et argument" er fordi det finnes uendelig mange argumenter ved vinkelen $\theta + 2 \pi$. Dette skrives $\arg Z = \theta$. Fra dette har vi altså

\begin{aligned}
a & = \left| Z \right| \cdot \cos \theta \\
 b & = \left| Z \right| \cdot \sin \theta \\
 Z & = \left| Z \right| \left(\cos \theta + i \sin \theta\right)
\end{aligned}

Komplekse tall på polarform skrives vanligvis forenklet som $Z = \left| Z \right| \cdot e^{i \theta}$. Ofte ønsker man å skrive om komplekse tall til polarform slik at det er enklere å jobbe med.

* Regneregler

Regnereglene for komplekse tall er stort sett det samme som med reelle tall, så de fleste regnereglene er trivielle.

** Addisjon

\begin{aligned}
Z & = a + i b \\
 W & = c + i d \\
 Z \pm W & = \left(a + i b\right) \pm \left(c + i d\right) \\
 & = \left(a \pm c\right) + i \left(b \pm d\right)
\end{aligned}

** Multiplikasjon

Den distributive lov gjelder også for komplekse tall.

\begin{aligned}
Z \cdot W & = \left(a + i b\right) \cdot \left(c + i d\right) \\
 & = a c + i a d + i b c + i^2 b d \\
 & = \left(a c - b d\right) + i \left(a d + b c\right)
\end{aligned}

En viktig identitet man får fra dette og konjugatsetningen er:

\begin{aligned}
Z \cdot \overline{Z} & = \left(a + i b\right) \left(a - i b\right) \\
 & = a^2 - i^2 b^2 \\
 & = a^2 + b^2 = \left| Z \right|^2
\end{aligned}

Ved hjelp av denne identiteten kan vi også finne en regel for divisjon:

\begin{aligned}
\frac{W}{Z} & = \frac{W \cdot \overline{Z}}{Z \cdot \overline{Z}} \\
 & = \left(c + i d\right)\frac{a - i b}{a^2 + b^2} \\
 & = \frac{c a + i d a - i c b - i^2 d b}{a^2 + b^2} \\
 & = \frac{\left(c a + d b\right) + i \left(d a - c b\right)}{a^2 + b^2} \\
 & = \frac{c a + d b}{a^2 + b^2} + i \frac{d a - c b}{a^2 + b^2}
\end{aligned}

*** Geometrisk tolkning av multiplikasjon

Vi kan skrive på polarform:

\begin{aligned}
Z & = \left| Z \right| e^{i \theta} \\
 W & = \left| W \right| e^{i \varphi} \\
 Z \cdot W & = \mid Z\\mid W \mid e^{i \left(\theta + \varphi\right)}
\end{aligned}

Altså har vi at:

\begin{aligned}
\left| Z \cdot W \right| & = \mid Z\\mid W \mid \\
 \arg \left(Z \cdot W\right) & = \arg Z + \arg W
\end{aligned}

Dette er også et eksempel på hvordan notasjonen $e^{i \varphi}$ gjør det betydelig enklere å jobbe med.

-----

Fra /De Moivres formel/ har vi også at $\left(e^{i \theta}\right)^n = e^{i n \theta}$.

* Røtter til komplekse tall

Gitt $Z \in \mathbb{C}$, løs likningen $W^n = Z$ for $W$. Dette kallse /n-te røtter/ til $Z$. Vi definerer $Z = \left| Z \right| \cdot e^{i \theta}$ og $W = \left| W \right| \cdot e^{i \varphi}$. Vi kan da løse likningen

\begin{aligned}
W^n & = Z \\
 \left| W \right|^n \cdot \left(e^{i \varphi}\right)^n & = \left| Z \right| e^{i \theta} \\
 \left| W \right|^n \cdot e^{i \varphi n} & = \left| Z \right| e^{i \theta}
\end{aligned}

Fra dette har vi at modulus kan skrives som $\left| W \right| = \sqrt[n]{\left| Z \right|}$. Videre kan vi skrive vinkelen som $\varphi = \frac{\theta}{n} + k \frac{2 \pi}{n} , \quad k \in \mathbb{Z}$. Dette er fordi et komplekst tall kan ha flere røtter. Mer spesifikt har det $n$ $n$-te røtter. Dette er fordi $k = n$ gir $\varphi = \frac{\theta}{n} + 2 \pi$, som er lik et helt omløp. Altså vil resultatene gjentas.

For hver nye rot har vi $\theta_i = \theta_{i - 1} + \frac{2 \pi}{n}$. Altså kan vi skrive at $W_{k + 1} = W_k \cdot e^{i \frac{2 \pi}{n}}$.

* Faktorisering av polynomer

Algebraens fundamentalteorem sier at et polynom er definert ved

\[
P_n \left(x\right) = c_n x^n + \ldots + c_1 x + c_0 , \quad c_n \in \mathbb{C} , n \in \mathbb{N}
\]

Dette kalles et polynom av grad $n$. Vi har at $\exists Z \in \mathbb{C} \, \forall P_n$ slik at $P\left(Z\right) = 0$. $Z$ kalles en /rot/ eller et /nullpunkt/. For eksempel: $x^2 + 1 = 0 \Rightarrow x = \pm i$.

Videre har vi /faktorteoremet/. Hvis $a$ er en rot til $P\left(x\right)$, deler $\left(x - a\right)$ polynomet. Det vil si at $P\left(x\right) = \left(x - a\right) \cdot Q\left(x\right)$ der $Q\left(x\right)$ er et polynom med grad $n - 1$. Dermed har vi at $\exists a_1 , a_2 , \ldots , a_n \in \mathbb{C} \, \forall P_n$ slik at $P\left(x\right) = \left(x - a_1\right)\left(x - a_2\right) \ldots \left(x - a_n\right)$. Det vil si at $P\left(x\right)$ kan faktoriseres over $\mathbb{C}$ i lineære faktorer.

-----

Vi har at $P\left(x\right)$ er et reelt polynom og $P\left(Z\right)= 0$ og $P\left(\overline{Z}\right)= 0$. $Z \notin \mathbb{R} \Leftrightarrow Z \neq \overline{Z}$. Altså er $\left(x - Z\right)$ og $\left(x - \overline{Z}\right)$ faktorer. Det vil si at $\left(x - Z\right)\left(x -\overline{Z}\right)$ deler $P\left(x\right)$. Vi kan videre finne et uttrykk med kun reelle koeffisienter ved

\begin{aligned}
\left(x - Z\right)\left(x -\overline{Z}\right) & = x^2 - \left(Z + \overline{Z}\right) x + Z \overline{Z} \\
 & = x^2 - 2 a x + a^2 + b^2
\end{aligned}

$\Rightarrow$ Et reelt polynom $P\left(x\right)$ kan faktoriseres over $\mathbb{R}$ i lineære og kvadratiske faktorer, ved å kombinere to og to imaginære ledd.

*** Eksempel

Faktoriser $P\left(x\right) = x^4 + 2 x^3 + 4 x^2 + 2 x + 3$ over $\mathbb{C}$ og over $\mathbb{R}$. Vi har gitt at $P\left(i\right) = 0$.

Vet at $P\left(Z\right) = 0 \Leftrightarrow P\left(\overline{Z}\right) = 0 \Rightarrow P\left(- i\right) = 0$. Dermed har vi at $\left(x - i\right)\left(x + i\right) = x^2 + 1$ deler $P\left(x\right)$. Da kan vi gjøre polynomdivisjon på uttrykket og få $P\left(x\right) = \left(x^2 + 1\right)\left(x^2 + 2 x + 3\right)$. Faktoriserer dette videre:

\begin{aligned}
x^2 + 2 x + 3 & = 0 \\
 x & = \frac{- 2 \pm \sqrt{- 8}}{2} \\
 & = \frac{- 2 \pm 2 i \sqrt{2}}{2} \\
 & = - 1 \pm \sqrt{2} i \\
 x^2 + 2 x + 3 & = \left(x - 1 - \sqrt{2} i\right)\left(x + 1 + \sqrt{2} i\right)
\end{aligned}

Resultatet blir da at $P\left(x\right)$ faktorisert over $\mathbb{C}$ er $\left(x - 1\right)\left(x + 1\right)\left(x - 1 -\sqrt{2} i\right)\left(x + 1 +\sqrt{2} i\right)$, og $P\left(x\right)$ faktorisert over $\mathbb{R}$ er $\left(x^2 + 1\right)\left(x^2 + 2 x + 3\right)$.

* Oppgaver

** Appendix I, oppg 46

Express each of the complex numbers $z = 3 + i \sqrt{3}$ and $w = - 1 + i \sqrt{3}$ in polar form. Use these expressions to calculate $z w$ and $\frac{z}{w}$.

Vi har to komplekse tall i algebraisk form. For å finne produktet og kvotienten må vi først skrive om til polarform:

\begin{aligned}
\left| Z \right| & = \sqrt{3^2 + \sqrt{3}^2} = \sqrt{12} = 2 \sqrt{3} \\
 \arg Z & = \tan^{- 1} \frac{\sqrt{3}}{3} = \frac{\pi}{6} \\
 Z & = 2 \sqrt{3} e^{i \frac{\pi}{6}} \\
 \left| W \right| & = \sqrt{\left(- 1\right)^2 + \sqrt{3}^2} = \sqrt{4} = 2 \\
 \tan^{- 1} \frac{\sqrt{3}}{- 1} & = - \frac{\pi}{3} \\
 \arg W & = \pi - \frac{\pi}{3} = 2 \frac{\pi}{3} \\
 W & = 2 e^{i \frac{2 \pi}{3}}
\end{aligned}

Videre beregner produktet:

\begin{aligned}
\left| Z \cdot W \right| & = \left| Z \right| \cdot \left| W \right| = 4 \sqrt{3} \\
 \arg Z \cdot W = \arg Z + \arg W = \frac{\pi}{6} + \frac{2 \pi}{3} = \frac{5 \pi}{6} \\
 Z \cdot W & = 4 \sqrt{3} e^{\frac{5\pi}{6} i}
\end{aligned}

Og til slutt kvotienten:

\begin{aligned}
\left|\frac{Z}{W} \right| & = \left| Z\frac{\right|}{\left|} W \right| = \frac{2 \sqrt{3}}{2} = \sqrt{3} \\
 \arg \frac{Z}{W} & = \arg Z - \arg W \\
 & = \frac{\pi}{6} - \frac{2\pi}{3} = \frac{- 3\pi}{6} = -\frac{\pi}{2} \\
 \frac{Z}{W} & = \sqrt{3} e^{-\frac{\pi}{2} i}
\end{aligned}

** Appendix I, oppg 53

Find the three cube roots of $- 1 + i$.

\begin{aligned}
w^3 & = - 1 + i \\
 w^3 & = \sqrt{2} e^{\frac{3 \pi}{4} i} \\
 \left| W_k \right| & = \sqrt[3]{\sqrt{2}} = \sqrt[6]{2} \\
 \arg W_k & = \frac{3\pi}{4} \cdot \frac{1}{3} + \frac{k 2 \pi}{3} \\
 W_0 & = \sqrt[6]{2} e^{i \frac{\pi}{4}} \\
 W_1 & = \sqrt[6]{2} e^{i \frac{11\pi}{12}} \\
 W_3 & = \sqrt[6]{2} e^{i \frac{19\pi}{12}} = \sqrt[6]{2} e^{-\frac{5\pi}{12}}
\end{aligned}

** P6 - 25

Vis at $P\left(Z\right) = 0 \Leftrightarrow P\left(\overline{Z}\right) = 0$.

Vi har gitt at:

\begin{aligned}
\overline{Z} + \overline{W} & = \overline{Z + W} \\
 \overline{Z} + \overline{W} & = \overline{Z W} \\
 P\left(Z\right) & = 0 \\
 x & = \overline{x} \; \forall x \in \mathbb{R}
\end{aligned}

Kan da sette opp:

\begin{aligned}
P\left(x\right) & = a_0 + a_1 x + a_2 x^2 + \ldots + a_n x^n \\
 P\left(\overline{Z}\right) & = a_0 + a_1 \overline{Z} + a_2 \overline{Z}^2 + \ldots + a_n \overline{Z}^n \\
 & = a_0 + a_1 \overline{Z} + a_2 \overline{Z^2} + \ldots ´ a_n \overline{Z^n} \\
 & = \overline{a_0} + \overline{a_1 Z} + \overline{a_2 Z^2} + \ldots + \overline{a_n Z^n} \\
 & = \overline{a_0 + a_1 Z + a_2^2 + \ldots + a_n Z^n} \\
 P\left(\overline{Z}\right) & = \overline{P\left(Z\right)} = \overline{0} = 0
\end{aligned}
