name: Generate static org-roam-ui page

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ORUI
        # uses: ikoamu/org-roam-ui-hosting@main
        uses: ./actions/publish-orui
        with:
          org-roam-directory: org
          org-roam-db-filename: org-roam.db
          site-title: "Org notes"
          deploy-to-pages: false

      - name: Inject orui-config.html into index.html
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');

            const indexPath = './ui/standalone/out/index.html';
            const configPath = './orui-config.html';

            if (fs.existsSync(indexPath) && fs.existsSync(configPath)) {
              let html = fs.readFileSync(indexPath, 'utf8');
              const customConfig = fs.readFileSync(configPath, 'utf8');
              html = html.replace('<head>', '<head>' + customConfig);
              fs.writeFileSync(indexPath, html, 'utf8');
              console.log('Successfully injected orui-config.html into index.html');
            } else {
              console.error('Missing index.html or orui-config.html file.');
              process.exit(1);
            }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./ui/standalone/out"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
